# Generated by Django 2.0.13 on 2019-06-11 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20190611_0822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='login',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 8, 25, 11, 619871, tzinfo=utc)),
        ),
    ]
