# Generated by Django 2.0.13 on 2019-06-11 11:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_auto_20190611_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 11, 10, 15, 638625, tzinfo=utc)),
        ),
    ]
