# Generated by Django 2.0.13 on 2019-06-11 13:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_auto_20190611_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 13, 31, 33, 401582, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='task',
            name='prioprity',
            field=models.CharField(choices=[('L', 'low'), ('M', 'medium'), ('H', 'high')], default='L', max_length=50),
        ),
    ]
