# Generated by Django 2.0.13 on 2019-06-11 17:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0008_auto_20190611_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 17, 30, 1, 54939, tzinfo=utc)),
        ),
    ]
