# Generated by Django 2.0.13 on 2019-06-11 20:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_auto_20190611_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 12, 20, 44, 48, 650861, tzinfo=utc)),
        ),
    ]
