# Generated by Django 2.0.13 on 2019-06-12 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20190611_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 13, 5, 41, 10, 714170, tzinfo=utc)),
        ),
    ]
