# Generated by Django 2.0.13 on 2019-06-13 05:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_auto_20190612_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 5, 41, 8, 301538, tzinfo=utc)),
        ),
    ]
