# Generated by Django 2.0.13 on 2019-06-13 22:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0013_auto_20190613_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='prioprity',
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(choices=[(3, 'Low'), (2, 'Medium'), (1, 'High')], default=3),
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 22, 4, 8, 970975, tzinfo=utc)),
        ),
    ]
