# Generated by Django 2.0.13 on 2019-06-13 22:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20190613_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 14, 22, 10, 3, 532831, tzinfo=utc)),
        ),
    ]
