# Generated by Django 2.0.13 on 2019-06-14 05:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0016_auto_20190613_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 15, 5, 43, 44, 291951, tzinfo=utc)),
        ),
    ]
