# Generated by Django 2.0.13 on 2019-06-17 04:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0017_auto_20190614_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='acomplish_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 18, 4, 1, 18, 57684, tzinfo=utc)),
        ),
    ]
